### ISSUE TITLE
Synaptic driver missing in TuxedoOS 2 after webFAI installation

### ISSUE THREAD

**Issue by TheRealAgentK** [tuxedocomputers/tuxedo-tomte#27] opened 2023-09-09 02:30 UTC
Logging this here, but feel free to move if better placed in a different project.

Installed Tuxedo OS 2 (22.04) via webFAI on an InfinityBook Pro 15v5 (based on the Clevo N15xCU).

Post-install, when setting up the touchpad for my needs, none of the tapping settings in System Settings -> Input Devices -> Touchpad were able to be ticked, all greyed out.

Installing the Synaptics touchpad driver (`xserver-xorg-input-synaptics`) and a reboot fixed that and it's all working now as intended, but this driver should probably be preinstalled via webFAI or tomte for this machine.

**Comment by tuxedo-ma** [comment] 2023-11-23 11:13
Hi @TheRealAgentK ,

Thank you for bringing this touchpad configuration issue to our attention. We appreciate your detailed report regarding the installation of Tuxedo OS 2 (22.04) on the InfinityBook Pro 15v5.

We're glad to hear that you were able to resolve the problem by installing the Synaptics touchpad driver (xserver-xorg-input-synaptics) and that the touchpad is now functioning as intended. Your proactive approach to finding a solution and sharing it is invaluable to both our team and the wider community.

Your suggestion about preinstalling the Synaptics touchpad driver via webFAI or tomte for the Clevo N15xCU-based machines is well-noted. I'll pass this information for consideration in future releases. Your contributions help us improve the overall user experience, and we are grateful for your dedication to making Tuxedo OS even better.

If you encounter any further issues or have additional feedback, please don't hesitate to let us know. We appreciate your support and collaboration in making Tuxedo OS a more robust and user-friendly operating system.

Thank you once again for your time and effort in reporting and resolving this issue.

Best regards,
M. Arnold

**Comment by tuxedo-ma** [comment] 2023-11-23 16:05
Hi @TheRealAgentK ,
We've attempted to replicate the issue on same hardware specifications but couldn't observe the same behavior without installing the Synaptics touchpad driver (xserver-xorg-input-synaptics). It's positive to hear that installing this driver resolved the problem for you.

While we couldn't reproduce the issue, we thank you for telling us. To address this concern and ensure a smoother user experience, we recommend reaching out to our support. They might provide insights or solutions tailored to your specific hardware configuration.

If you encounter any further issues or have additional insights, please don't hesitate to share them with us.

Thank you for your valuable contribution to the Tuxedo OS community.

Best regards,
M. Arnold

**Closed as completed by tuxedo-ma** 2023-11-23 16:05 UTC
